### PR TITLE
Add tests for boolean ops

### PR DESCRIPTION
**Pull request by kwannoel**

### CODE REVIEW

**Comment by thomastanck** [comment]
I realised this a little late but the boolean ops need to implement shortcircuiting, so it's actually a special form

https://docs.racket-lang.org/reference/if.html#%28form._%28%28lib._racket%2Fprivate%2Fletstx-scheme..rkt%29._or%29%29

Could you help implement that behaviour? You'll need to add the syntaxes to `evaluator/special-form.ts` and then implement the behaviour in `evaluator/evaluator.ts`. After that you can add the tests to `evaluator/__tests__/special-form.ts`

Also, could you move the tests for the other primitives (list ops and comparisons) to `__tests__/primitives.ts`

You're also missing some tests: https://coveralls.io/builds/37324362/source?filename=src%2Fevaluator%2Fprimitives.ts#L10

and some cases: https://coveralls.io/builds/37324362/source?filename=src%2Fevaluator%2Fprimitives.ts#L634

**Comment by kwannoel** [comment]
> I realised this a little late but the boolean ops need to implement shortcircuiting, so it's actually a special form
> 
> https://docs.racket-lang.org/reference/if.html#%28form._%28%28lib._racket%2Fprivate%2Fletstx-scheme..rkt%29._or%29%29
> 
> Could you help implement that behaviour? You'll need to add the syntaxes to `evaluator/special-form.ts` and then implement the behaviour in `evaluator/evaluator.ts`. After that you can add the tests to `evaluator/__tests__/special-form.ts`
> 
> Also, could you move the tests for the other primitives (list ops and comparisons) to `__tests__/primitives.ts`
> 
> You're also missing some tests: https://coveralls.io/builds/37324362/source?filename=src%2Fevaluator%2Fprimitives.ts#L10
> 
> and some cases: https://coveralls.io/builds/37324362/source?filename=src%2Fevaluator%2Fprimitives.ts#L634

@thomastanck anyway to check the specific tests / cases?

**Comment by kwannoel** [comment]
> I realised this a little late but the boolean ops need to implement shortcircuiting, so it's actually a special form
> 
> https://docs.racket-lang.org/reference/if.html#%28form._%28%28lib._racket%2Fprivate%2Fletstx-scheme..rkt%29._or%29%29
> 
> Could you help implement that behaviour? You'll need to add the syntaxes to `evaluator/special-form.ts` and then implement the behaviour in `evaluator/evaluator.ts`. After that you can add the tests to `evaluator/__tests__/special-form.ts`
> 
> Also, could you move the tests for the other primitives (list ops and comparisons) to `__tests__/primitives.ts`
> 
> You're also missing some tests: https://coveralls.io/builds/37324362/source?filename=src%2Fevaluator%2Fprimitives.ts#L10
> 
> and some cases: https://coveralls.io/builds/37324362/source?filename=src%2Fevaluator%2Fprimitives.ts#L634

@thomastanck Where are these `list ops` and `comparisons` tests? Can't find these in `__tests__/evaluator.ts`.

**Comment by thomastanck** [comment]
> @thomastanck anyway to check the specific tests / cases?

add tests so the lines i linked are at least covered. some of these aren't trivial error handling code either, so definitely test them. uncovered code is always untested. (the converse is not true)

> @thomastanck Where are these `list ops` and `comparisons` tests? Can't find these in `__tests__/evaluator.ts`.
> 
> For `boolean ops` ill work on it in a separate PR.

add them to the bottom of the file

**Review by thomastanck — APPROVED** [review]

**Pull request merged**
